"""Counterfact dashboard. Reads the audit store and the report tables only; never the simulator.

Run: ``uv run streamlit run dashboard/app.py`` (after ``make eval`` and ``make demo``).
"""

from __future__ import annotations

import json

import matplotlib
import pandas as pd
import streamlit as st

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

from counterfact.agent.audit import AuditStore  # noqa: E402
from counterfact.agent.explain import ClaudeExplainer, TemplateExplainer  # noqa: E402
from counterfact.config import ARMS, POLICY_Z, ROOT, get_settings  # noqa: E402

SETTINGS = get_settings()
TABLES = SETTINGS.reports_dir / "tables"
FIGURES = SETTINGS.reports_dir / "figures"
AUDIT_ROOT = SETTINGS.reports_dir / "audit"
BLUE, ORANGE, AQUA, GRAY, INK, MUTED = "#2a78d6", "#eb6834", "#1baf7a", "#9a9891", "#0b0b0b", "#52514e"
POLICY_COLOR = {"ml_policy": BLUE, "heuristic": ORANGE, "oracle": AQUA}

st.set_page_config(page_title="Counterfact", page_icon="₹", layout="wide")


@st.cache_data
def load_csv(name: str) -> pd.DataFrame | None:
    p = TABLES / name
    return pd.read_csv(p) if p.exists() else None


def rs(x: float) -> str:
    return f"Rs {x:,.0f}"


def lakh(x: float) -> str:
    return f"Rs {x / 1e5:,.1f} L"


paired = load_csv("ab_paired.csv")
ab = load_csv("ab_ab.csv")
per_merchant = load_csv("ab_per_merchant.csv")
arm_mix = load_csv("ab_arm_mix.csv")
guard = load_csv("ab_guardrails.csv")
abst = load_csv("ab_abstention.csv")
ope = load_csv("ope.csv")
sens = load_csv("sensitivity.csv")
dial = load_csv("z_dial.csv")

st.title("Counterfact")
st.caption("Net-expected-value recovery of failed subscription payments. \"Do nothing\" is a first-class action with its own expected value.")

if paired is None:
    st.warning("No report tables found. Run `make data && make train && make eval` first.")
    st.stop()

variants = list(paired["variant"].unique())
with st.sidebar:
    st.header("View")
    variant = st.selectbox("Simulator variant", variants, index=0)
    runs = sorted([p for p in AUDIT_ROOT.glob("*") if (p / "audit.db").exists()], key=lambda p: p.stat().st_mtime, reverse=True) if AUDIT_ROOT.exists() else []
    run_dir = st.selectbox("Audit run", runs, format_func=lambda p: p.name) if runs else None
    st.markdown(f"Shipped policy: gated ensemble, z = {POLICY_Z}")
    st.markdown("Every number here is regenerated by `make eval`, `make dial`, `make sensitivity`, `make demo`.")

P = paired[paired["variant"] == variant].set_index("policy")
ml, rz, heur = P.loc["ml_policy"], P.loc["razorpay_default"], P.loc["heuristic"]
A = ab[(ab["variant"] == variant) & (ab["policy"] == "ml_policy")].iloc[0]
AB_T = abst[abst["variant"] == variant].iloc[0]

# ---- headline ----------------------------------------------------------------------------------
st.subheader(f"Headline ({variant}, 20k-failure holdout, per 1,000 failures)")
c1, c2, c3, c4, c5, c6 = st.columns(6)
c1.metric("Revenue at risk", lakh(ml["rs_at_risk_per_1k"]) if "rs_at_risk_per_1k" in ml else "n/a")
c2.metric("Recovered: ML policy", lakh(ml["rs_recovered_per_1k"]), delta=f"{ml['paired_recovery_delta']:+.1%} recovery vs Razorpay default")
c3.metric("Recovered: Razorpay default", lakh(rz["rs_recovered_per_1k"]), delta=f"{rz['recovery_rate']:.1%} raw recovery", delta_color="off")
c4.metric("Incremental vs Razorpay default", lakh(ml["paired_exact_per_1k"]), delta=f"A/B {lakh(A['incr_vs_control_per_1k'])} [{lakh(A['ci_low'])}; {lakh(A['ci_high'])}]", delta_color="off")
c5.metric("Contacts saved vs rule table", f"{heur['contacts_per_1k'] - ml['contacts_per_1k']:,.0f} / 1k", delta=f"wasted-contact rate {ml['wasted_contacts_per_1k'] / max(ml['contacts_per_1k'], 1):.0%} vs {heur['wasted_contacts_per_1k'] / max(heur['contacts_per_1k'], 1):.0%}", delta_color="off")
c6.metric("Abstention", f"{ml['no_action_share']:.1%}", delta=f"no_action was right {AB_T['self_recovered']:.0%} of the time", delta_color="off")

# ---- A/B chart ---------------------------------------------------------------------------------
left, right = st.columns([3, 2])
with left:
    st.markdown("**Incremental rupees vs Razorpay default (paired exact); dot = two-arm randomized A/B with 95% CI**")
    order = [p for p in ("ml_policy", "heuristic", "razorpay_t123", "oracle") if p in P.index]
    fig, ax = plt.subplots(figsize=(7, 3))
    y = list(range(len(order)))
    ax.barh(y, [P.loc[p, "paired_exact_per_1k"] / 1e5 for p in order], color=[POLICY_COLOR.get(p, GRAY) for p in order], height=0.6)
    i = order.index("ml_policy")
    est = A["incr_vs_control_per_1k"] / 1e5
    ax.errorbar([est], [i], xerr=[[est - A["ci_low"] / 1e5], [A["ci_high"] / 1e5 - est]], fmt="o", color=INK, capsize=4)
    ax.set_yticks(y)
    ax.set_yticklabels({"ml_policy": "ML policy", "heuristic": "rule table (guardrailed)", "razorpay_t123": "literal T+1/T+2/T+3", "oracle": "oracle (true probabilities)"}[p] for p in order)
    ax.invert_yaxis()
    ax.axvline(0, color=MUTED, lw=1)
    ax.spines[["top", "right"]].set_visible(False)
    ax.grid(axis="x", color="#e5e4e0", lw=0.6)
    ax.set_xlabel("Rs lakh per 1,000 failures")
    fig.tight_layout()
    st.pyplot(fig, use_container_width=True)
    plt.close(fig)
with right:
    st.markdown("**All policies**")
    show = P.reset_index()[["policy", "paired_exact_per_1k", "recovery_rate", "no_action_share", "contacts_per_1k", "wasted_contacts_per_1k", "escalations_per_1k"]]
    show = show.rename(columns={"paired_exact_per_1k": "Rs incr /1k", "recovery_rate": "recovery", "no_action_share": "abstention", "contacts_per_1k": "contacts /1k", "wasted_contacts_per_1k": "wasted /1k", "escalations_per_1k": "escalations /1k"})
    st.dataframe(show.style.format({"Rs incr /1k": "{:,.0f}", "recovery": "{:.1%}", "abstention": "{:.1%}", "contacts /1k": "{:.0f}", "wasted /1k": "{:.0f}", "escalations /1k": "{:.0f}"}), hide_index=True, use_container_width=True)

# ---- arms, merchants, guardrails ----------------------------------------------------------------
t1, t2, t3, t4, t5 = st.tabs(["Per arm", "Per merchant", "Guardrails", "OPE vs truth", "Sensitivity & dial"])
with t1:
    mix = arm_mix[arm_mix["variant"] == variant].sort_values("share", ascending=False)
    ca, cb = st.columns(2)
    with ca:
        st.markdown("**Arm mix (ML policy on the holdout)**")
        fig, ax = plt.subplots(figsize=(5, 3))
        ax.barh(range(len(mix)), mix["share"] * 100, color=BLUE, height=0.6)
        ax.set_yticks(range(len(mix)))
        ax.set_yticklabels(mix["action"])
        ax.invert_yaxis()
        ax.spines[["top", "right"]].set_visible(False)
        ax.set_xlabel("% of failures")
        fig.tight_layout()
        st.pyplot(fig, use_container_width=True)
        plt.close(fig)
    with cb:
        st.markdown("**Per-arm outcomes in the selected audit run**")
        if run_dir is not None:
            store = AuditStore(run_dir)
            rows = pd.DataFrame(store.all_decisions())
            if len(rows):
                rows["recovered"] = rows["outcome"].map(lambda o: bool(o.get("recovered")) if isinstance(o, dict) else None)
                rows["recovered_amount"] = rows["outcome"].map(lambda o: float(o.get("recovered_amount", 0)) if isinstance(o, dict) else 0.0)
                g = rows.groupby("action_name").agg(n=("event_id", "count"), recovery=("recovered", "mean"), rs_recovered=("recovered_amount", "sum"), rs_at_risk=("amount", "sum")).sort_values("n", ascending=False)
                st.dataframe(g.style.format({"recovery": "{:.1%}", "rs_recovered": "{:,.0f}", "rs_at_risk": "{:,.0f}"}), use_container_width=True)
        else:
            st.info("Run `make demo` to create an audit run.")
with t2:
    pm = per_merchant[(per_merchant["variant"] == variant) & per_merchant["policy"].isin(["ml_policy", "heuristic", "oracle"])]
    pv = pm.pivot(index="merchant_id", columns="policy", values="incr_vs_control_per_1k")
    st.markdown("**Rs incremental vs Razorpay default per 1,000, by merchant and policy (paired exact)**")
    st.dataframe(pv.style.format("{:,.0f}"), use_container_width=True)
    st.dataframe(pm[["merchant_id", "policy", "recovery_rate", "contacts_per_1k", "escalations_per_1k", "no_action_share"]].style.format({"recovery_rate": "{:.1%}", "contacts_per_1k": "{:.0f}", "escalations_per_1k": "{:.0f}", "no_action_share": "{:.1%}"}), hide_index=True, use_container_width=True)
with t3:
    gv = guard[guard["variant"] == variant]
    st.markdown("**Guardrail rejections per 1,000 failures (ML policy). Every code is machine-readable and lands in the audit row.**")
    st.dataframe(gv[["code", "count", "per_1k"]].style.format({"per_1k": "{:.1f}"}), hide_index=True)
    st.markdown("**Abstentions: was `no_action` right?**")
    st.dataframe(abst[abst["variant"] == variant].style.format({"abstention_share": "{:.1%}", "self_recovered": "{:.1%}", "razorpay_would_recover": "{:.1%}", "mean_amount_abstained": "{:,.0f}", "foregone_per_1k": "{:,.0f}"}), hide_index=True)
with t4:
    if ope is not None:
        ov = ope[(ope["variant"] == variant) & (ope["reward"] == "rupees")]
        st.markdown("**Off-policy estimates from logged data vs paired-exact truth vs randomized A/B (rupees per 1,000)**")
        cols = ["policy", "match_rate", "ess", "truth", "ips", "snips", "dm", "dr", "dr_err_pct", "dr_diff_vs_razorpay", "ab_diff", "ab_ci_low", "ab_ci_high", "dr_within_ab_ci"]
        st.dataframe(ov[cols].style.format({"match_rate": "{:.1%}", "ess": "{:,.0f}", "truth": "{:,.0f}", "ips": "{:,.0f}", "snips": "{:,.0f}", "dm": "{:,.0f}", "dr": "{:,.0f}", "dr_err_pct": "{:+.1f}%", "dr_diff_vs_razorpay": "{:,.0f}", "ab_diff": "{:,.0f}", "ab_ci_low": "{:,.0f}", "ab_ci_high": "{:,.0f}"}), hide_index=True, use_container_width=True)
    else:
        st.info("Run `python scripts/ope.py --all-variants`.")
with t5:
    if (FIGURES / "z_dial.png").exists():
        st.image(str(FIGURES / "z_dial.png"), caption="Conservatism dial: lift when uplift is real vs abstention when nothing works, as the gate z varies")
    if sens is not None:
        st.markdown("**Sensitivity: every simulator assumption that moves the headline (calibrated world regenerated, models retrained per row)**")
        st.dataframe(sens[["setting", "value", "control_recovery", "ml_incr_per_1k", "heuristic_incr_per_1k", "oracle_incr_per_1k", "ml_abstention", "ml_contacts_per_1k", "ranking_holds", "ml_vs_heuristic"]].style.format({"control_recovery": "{:.1%}", "ml_incr_per_1k": "{:,.0f}", "heuristic_incr_per_1k": "{:,.0f}", "oracle_incr_per_1k": "{:,.0f}", "ml_abstention": "{:.1%}", "ml_contacts_per_1k": "{:.0f}"}), hide_index=True, use_container_width=True)

# ---- decision explorer ----------------------------------------------------------------------------
st.subheader("Decisions: click through to the audit row")
if run_dir is None:
    st.info("Run `make demo` to create an audit run, then pick it in the sidebar.")
else:
    store = AuditStore(run_dir)
    m = store.metrics()
    k1, k2, k3, k4, k5 = st.columns(5)
    k1.metric("Decisions", m["decisions"])
    k2.metric("Recovered", f"{m['recovered']}/{m['outcomes_known']}", delta=f"{(m['recovery_rate'] or 0):.1%}", delta_color="off")
    k3.metric("Rs recovered", rs(m["rs_recovered"]), delta=f"of {rs(m['rs_at_risk'])} at risk", delta_color="off")
    k4.metric("Contacts / escalations / abstentions", f"{m['contacts']} / {m['escalations']} / {m['abstentions']}")
    k5.metric("Executor ledger", json.dumps(m["executor"]))
    rows = pd.DataFrame(store.recent(limit=500))
    if len(rows):
        rows["executor_status"] = rows["executor_result"].map(lambda r: r.get("status") if isinstance(r, dict) else None)
        rows["recovered"] = rows["outcome"].map(lambda o: o.get("recovered") if isinstance(o, dict) else None)
        st.dataframe(rows[["event_id", "merchant_id", "failure_category", "amount", "action_name", "overridden", "rejection_codes", "executor_status", "recovered", "reason"]], hide_index=True, use_container_width=True, height=260)
        event_id = st.selectbox("Open decision", rows["event_id"].tolist())
        row = store.get(event_id)
        if row:
            a, b = st.columns([2, 3])
            with a:
                st.markdown(f"**{row['action_name']}** on a {rs(row['amount'])} {row['failure_category']} failure ({row['merchant_id']}, attempt {row['attempt_number']})")
                st.markdown(f"Reason: {row['reason']}")
                fig, ax = plt.subplots(figsize=(5, 2.6))
                ev = row["net_ev"]
                colors = [BLUE if i == row["chosen_arm"] else GRAY for i in range(5)]
                ax.barh(range(5), ev, color=colors, height=0.6)
                ax.set_yticks(range(5))
                ax.set_yticklabels(ARMS)
                ax.invert_yaxis()
                ax.axvline(0, color=MUTED, lw=1)
                ax.axvline(row.get("threshold") or 0, color=MUTED, lw=0.8, ls="--")
                ax.spines[["top", "right"]].set_visible(False)
                ax.set_xlabel("net expected value (Rs); dashed = merchant minimum")
                fig.tight_layout()
                st.pyplot(fig, use_container_width=True)
                plt.close(fig)
                st.caption(f"uplift per arm: {dict(zip(ARMS, row['uplift'], strict=True))}; P(recover | no_action) = {row.get('p_no_action_hat')}")
            with b:
                st.markdown("**Guardrail checks**")
                st.dataframe(pd.DataFrame(row["guardrail_checks"]), hide_index=True, use_container_width=True)
                st.markdown("**Executor**")
                st.json(row["executor_result"], expanded=False)
                st.markdown(f"**Outcome:** {row.get('outcome') or 'not yet known'}")
                st.markdown("**Explanation**")
                if row.get("explanation"):
                    st.write(row["explanation"])
                    st.caption(f"source: {row.get('explanation_source')}")
                elif st.button("Generate explanation", key=f"explain_{event_id}"):
                    explainer = ClaudeExplainer() if SETTINGS.anthropic_api_key else TemplateExplainer()
                    text, source = explainer.explain(row)
                    store.set_explanation(event_id, text, source)
                    st.write(text)
                    st.caption(f"source: {source}")
                else:
                    st.caption("Not generated yet (lazy; capped at 50 LLM calls per run; falls back to a template without an API key).")

st.divider()
st.markdown(
    "**Judging bars**  \n"
    "1. Money recovered across a batch: headline tiles and `make demo`.  \n"
    "2. Compliant escalation, stopping rules, audit trail: Guardrails tab and the decision explorer.  \n"
    "3. One failure handled gracefully: `make demo` injects a 5xx; the ledger shows queued -> re-driven with zero duplicate charges.  \n"
    "4. Every money action explainable, bounded, gated: net-EV chart, guardrail checks and the explanation on each decision.  \n"
    "5. Honest metrics: wasted contacts, abstention, null-uplift variant, OPE error, sensitivity table.  \n"
    "6. Razorpay test-mode APIs: `RazorpayExecutor` (`docs/ARCHITECTURE.md`)."
)
st.caption(f"Root: {ROOT}")
